<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Test Suite" tests="2" assertions="1" errors="2" failures="0" skipped="0" time="0.045393">
    <testsuite name="ActividadeControllerTest" file="C:\xampp\htdocs\sigepauta\tests\ActividadeControllerTest.php" tests="2" assertions="1" errors="2" failures="0" skipped="0" time="0.045393">
      <testcase name="testConstruct" class="ActividadeControllerTest" classname="ActividadeControllerTest" file="C:\xampp\htdocs\sigepauta\tests\ActividadeControllerTest.php" line="28" assertions="0" time="0.026433">
        <error type="PHPUnit\Framework\RiskyTestError">Risky Test
</error>
      </testcase>
      <testcase name="testCreate" class="ActividadeControllerTest" classname="ActividadeControllerTest" file="C:\xampp\htdocs\sigepauta\tests\ActividadeControllerTest.php" line="34" assertions="1" time="0.018960">
        <error type="PHPUnit\Framework\UnintentionallyCoveredCodeError">Risky Test
</error>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
